---
title: "Spring 2026"
---

- April 3: Pierre continues to present [A general perspective on the Metropolis-Hastings kernel](https://arxiv.org/abs/2012.14881) by Christophe Andrieu, Anthony Lee, Sam Livingstone. 15:00, Room 6 this time.

- March 27: [Shiva Darshan](https://shiva-darshan.github.io/) presents [A general perspective on the Metropolis-Hastings kernel](https://arxiv.org/abs/2012.14881) by Christophe Andrieu, Anthony Lee, Sam Livingstone. 15:00, Room 7.

- March 20: [Yvann le Fay](https://scholar.google.com/citations?user=YWU-jPUAAAAJ&hl=fr) presents on query complexity of Sequential Monte Carlo for normalising constants, joint work with [Nicolas Chopin](https://nchopin.github.io/). Room 3 at 15:00.

- March 13: [Mostly Monte Carlo](https://antoineluciano.github.io/mostlymontecarlo/sem/2026/s2026_03.html) at 15:00, Room 3, with [Pierre Del Moral](https://people.bordeaux.inria.fr/pierre.delmoral/biog.html) and [Bob Carpenter](https://bob-carpenter.github.io/).

- February 13: [All about that Bayes](https://sites.google.com/view/all-about-that-bayes/home) at Institut Henri Poincaré, from 14:00 to 17:00, Y Cauchois room. 
*The seminar is open to everyone, but please confirm your attendance by registering via [this link](https://evento.renater.fr/survey/registration-all-about-that-bayes-seminar-series-february-13-2026-qk9ylcgr).*


- February 6: [Pierre Jacob](https://pierrejacob.org) presents [On importance sampling and independent Metropolis-Hastings with an unbounded weight function](https://arxiv.org/abs/2411.09514), joint work with [George Deligiannidis](https://ziorzis.github.io/), [Mehdi Khribch](https://mehdi-khribch.github.io/) and [Guanyang Wang](https://guanyangwang.github.io/).

- January 30: Talk by [Victor Priser](https://victor-priser.github.io/). Room 6. Abstract: 

*Grid search and random search are widely used techniques for optimizing black-box functions when gradient information is unavailable. In these methods, a finite set of candidate points is evaluated, and the best-performing one is selected. We propose a simple and computationally inexpensive refinement of this paradigm: instead of selecting a single best point, we form a weighted average of the evaluated points, where the weights are chosen using an importance sampling scheme inspired by the Laplace principle. This scheme can be implemented as a post-processing step on top of random search, with no additional function evaluations. We also propose an iterative variant in which the sampling distributions are adaptively chosen to generate new candidate points around the previous estimate, in the spirit of Evolution Strategy (ES) methods. In a general non-convex setting, we show that after n evaluations, the error of the proposed methods is of smaller order than n^{-2/(d+2)}. This compares favorably with the n^{-1/d} rates of random search or grid search as soon as d > 2.*


- January 23: [Shiva Darshan](https://shiva-darshan.github.io/) presents
 [Explicit convergence bounds for Metropolis Markov chains: isoperimetry, spectral gaps and profiles](https://arxiv.org/abs/2211.08959) by Christophe Andrieu, Anthony Lee, Sam Power, Andi Q. Wang.